@startuml

!include SlicerProstate.puml
!include RegistrationResults.puml
!include SliceTrackerSession.puml
!include SliceTrackerPlugins.puml
!include SliceTrackerSteps.puml


ModuleWidgetMixin <|-- SliceTrackerWidget
SliceTrackerConstants <|-- SliceTrackerWidget


class SliceTrackerWidget {
  .. properties ..
  + session
  + stepManager
  --

  + enter(
  + setup()
  + cleanup()

}

SliceTrackerSession <.. SliceTrackerWidget::session: uses
SliceTrackerStepManager <.. SliceTrackerWidget::stepManager

@enduml
